import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Play, Square, Trash2, FileCode } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import StatusBadge from "@/components/StatusBadge";

export default function CodeSandbox() {
  const [isExecuting, setIsExecuting] = useState(false);
  const [output, setOutput] = useState<string[]>([]);

  // TODO: Remove mock data - replace with real code execution
  const mockCode = `// Generated by Code Generator Agent
function fibonacci(n) {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

// Calculate first 10 Fibonacci numbers
for (let i = 0; i < 10; i++) {
  console.log(\`F(\${i}) = \${fibonacci(i)}\`);
}`;

  const handleRun = () => {
    setIsExecuting(true);
    setOutput([]);
    
    // TODO: Replace with actual code execution via backend API
    setTimeout(() => {
      setOutput([
        "Executing code in sandbox...",
        "F(0) = 0",
        "F(1) = 1",
        "F(2) = 1",
        "F(3) = 2",
        "F(4) = 3",
        "F(5) = 5",
        "F(6) = 8",
        "F(7) = 13",
        "F(8) = 21",
        "F(9) = 34",
        "Execution completed successfully in 142ms"
      ]);
      setIsExecuting(false);
    }, 2000);
  };

  const handleStop = () => {
    setIsExecuting(false);
    setOutput(prev => [...prev, "Execution stopped by user"]);
  };

  return (
    <div className="h-screen flex flex-col">
      {/* Header */}
      <div className="p-6 border-b flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Code Sandbox</h1>
          <p className="text-sm text-muted-foreground">Safe execution environment for generated code</p>
        </div>
        <div className="flex items-center gap-2">
          <StatusBadge status={isExecuting ? "executing" : "idle"} />
          {isExecuting ? (
            <Button variant="destructive" onClick={handleStop} data-testid="button-stop">
              <Square className="w-4 h-4 mr-2" />
              Stop
            </Button>
          ) : (
            <Button onClick={handleRun} data-testid="button-run">
              <Play className="w-4 h-4 mr-2" />
              Run Code
            </Button>
          )}
        </div>
      </div>

      {/* Split View */}
      <div className="flex-1 grid grid-cols-2 divide-x">
        {/* Editor Panel */}
        <div className="flex flex-col">
          <div className="p-4 border-b flex items-center justify-between bg-card/50">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4" />
              <span className="text-sm font-medium font-mono">fibonacci.js</span>
            </div>
            <Button variant="ghost" size="sm">
              <Trash2 className="w-4 h-4" />
            </Button>
          </div>
          <ScrollArea className="flex-1">
            <div className="p-6">
              <pre className="font-mono text-sm">
                <code>{mockCode}</code>
              </pre>
            </div>
          </ScrollArea>
          <div className="p-2 border-t bg-card/50 flex items-center justify-between text-xs text-muted-foreground font-mono">
            <span>JavaScript</span>
            <span>12 lines</span>
          </div>
        </div>

        {/* Console Output Panel */}
        <div className="flex flex-col bg-card/50">
          <Tabs defaultValue="console" className="flex-1 flex flex-col">
            <TabsList className="w-full justify-start rounded-none border-b bg-transparent p-0">
              <TabsTrigger value="console" className="rounded-none">Console</TabsTrigger>
              <TabsTrigger value="errors" className="rounded-none">Errors</TabsTrigger>
              <TabsTrigger value="performance" className="rounded-none">Performance</TabsTrigger>
            </TabsList>
            <TabsContent value="console" className="flex-1 m-0">
              <ScrollArea className="h-full">
                <div className="p-4 font-mono text-sm space-y-1">
                  {output.length === 0 ? (
                    <p className="text-muted-foreground">Console output will appear here...</p>
                  ) : (
                    output.map((line, index) => (
                      <div key={index} className="py-0.5">
                        <span className="text-muted-foreground mr-2">{index + 1}</span>
                        <span>{line}</span>
                      </div>
                    ))
                  )}
                </div>
              </ScrollArea>
            </TabsContent>
            <TabsContent value="errors" className="flex-1 m-0">
              <div className="p-4">
                <p className="text-sm text-muted-foreground">No errors detected</p>
              </div>
            </TabsContent>
            <TabsContent value="performance" className="flex-1 m-0">
              <div className="p-4 space-y-4">
                <Card className="p-4">
                  <p className="text-sm text-muted-foreground mb-1">Execution Time</p>
                  <p className="text-2xl font-bold">142ms</p>
                </Card>
                <Card className="p-4">
                  <p className="text-sm text-muted-foreground mb-1">Memory Usage</p>
                  <p className="text-2xl font-bold">2.4 MB</p>
                </Card>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  );
}
